name: Video Server Rooms

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:12
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Running tests
      run: yarn test

